FROM node:9.3 as build-deps
LABEL maintainer="jordy@schreuders.it"
WORKDIR /usr/src
COPY package.json yarn.lock ./
RUN yarn
COPY . ./
RUN yarn build

FROM nginx:1.13
COPY --from=build-deps /usr/src/public /usr/share/nginx/html/public
